trigger_deb_build_pipeline:
  stage: deploy
  tags: [podman]
  script:
    - 'curl --fail --request POST --form token=$CI_JOB_TOKEN --form ref=master "https://gitlab.cambio-carsharing.com/api/v4/projects/49/trigger/pipeline"'
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
